from enum import Enum


class ItemClass(Enum):
    Normal = 0,
    Junk = 1,
    Priority = 2,
    Advancement = 3,


#    Item:                                             (type,       ItemClass,         GetItemID, special),
item_table = {
    'Bombs (5)':                                       ('Item',     ItemClass.Junk,         0x01, None),
    'Deku Nuts (5)':                                   ('Item',     ItemClass.Junk,         0x02, None),
    'Bombchus (10)':                                   ('Item',     ItemClass.Advancement,  0x03, None),
    'Boomerang':                                       ('Item',     ItemClass.Advancement,  0x06, None),
    'Deku Stick (1)':                                  ('Item',     ItemClass.Junk,         0x07, None),
    'Lens of Truth':                                   ('Item',     ItemClass.Advancement,  0x0A, None),
    'Megaton Hammer':                                  ('Item',     ItemClass.Advancement,  0x0D, None),
    'Cojiro':                                          ('Item',     ItemClass.Advancement,  0x0E, None),
    'Bottle':                                          ('Item',     ItemClass.Advancement,  0x0F, {'bottle': float('Inf')}),
    'Bottle with Milk':                                ('Item',     ItemClass.Advancement,  0x14, {'bottle': float('Inf')}),
    'Rutos Letter':                                    ('Item',     ItemClass.Advancement,  0x15, None),
    'Deliver Letter':                                  ('Item',     ItemClass.Advancement,  None, {'bottle': float('Inf')}),
    'Sell Big Poe':                                    ('Item',     ItemClass.Advancement,  None, {'bottle': float('Inf')}),
    'Magic Bean':                                      ('Item',     ItemClass.Advancement,  0x16, None),
    'Keaton Mask':                                     ('Item',     ItemClass.Normal,       0x1A, None),
    'Skull Mask':                                      ('Item',     ItemClass.Normal,       0x17, None),
    'Spooky Mask':                                     ('Item',     ItemClass.Normal,       0x18, None),
    'Bunny Hood':                                      ('Item',     ItemClass.Normal,       0x1B, None),
    'Mask of Truth':                                   ('Item',     ItemClass.Normal,       0x1C, None),
    'Pocket Egg':                                      ('Item',     ItemClass.Advancement,  0x1D, None),
    'Pocket Cucco':                                    ('Item',     ItemClass.Advancement,  0x1E, None),
    'Odd Mushroom':                                    ('Item',     ItemClass.Advancement,  0x1F, None),
    'Odd Potion':                                      ('Item',     ItemClass.Advancement,  0x20, None),
    'Poachers Saw':                                    ('Item',     ItemClass.Advancement,  0x21, None),
    'Broken Sword':                                    ('Item',     ItemClass.Advancement,  0x22, None),
    'Prescription':                                    ('Item',     ItemClass.Advancement,  0x23, None),
    'Eyeball Frog':                                    ('Item',     ItemClass.Advancement,  0x24, None),
    'Eyedrops':                                        ('Item',     ItemClass.Advancement,  0x25, None),
    'Claim Check':                                     ('Item',     ItemClass.Advancement,  0x26, None),
    'Kokiri Sword':                                    ('Item',     ItemClass.Advancement,  0x27, None),
    'Giants Knife':                                    ('Item',     ItemClass.Advancement,  0x28, None),
    'Deku Shield':                                     ('Item',     ItemClass.Normal,       0x29, None),
    'Hylian Shield':                                   ('Item',     ItemClass.Normal,       0x2A, None),
    'Mirror Shield':                                   ('Item',     ItemClass.Advancement,  0x2B, None),
    'Goron Tunic':                                     ('Item',     ItemClass.Advancement,  0x2C, None),
    'Zora Tunic':                                      ('Item',     ItemClass.Advancement,  0x2D, None),
    'Iron Boots':                                      ('Item',     ItemClass.Advancement,  0x2E, None),
    'Hover Boots':                                     ('Item',     ItemClass.Advancement,  0x2F, None),
    'Stone of Agony':                                  ('Item',     ItemClass.Advancement,  0x39, None),
    'Gerudo Membership Card':                          ('Item',     ItemClass.Advancement,  0x3A, None),
    'Heart Container':                                 ('Item',     ItemClass.Normal,       0x3D, None),
    'Piece of Heart':                                  ('Item',     ItemClass.Normal,       0x3E, None),
    'Boss Key':                                        ('BossKey',  ItemClass.Advancement,  0x3F, None),
    'Compass':                                         ('Compass',  ItemClass.Normal,       0x40, None),
    'Map':                                             ('Map',      ItemClass.Normal,       0x41, None),
    'Small Key':                                       ('SmallKey', ItemClass.Advancement,  0x42, {'progressive': float('Inf')}),
    'Weird Egg':                                       ('Item',     ItemClass.Advancement,  0x47, None),
    'Recovery Heart':                                  ('Item',     ItemClass.Junk,         0x48, None),
    'Arrows (5)':                                      ('Item',     ItemClass.Junk,         0x49, None),
    'Arrows (10)':                                     ('Item',     ItemClass.Junk,         0x4A, None),
    'Arrows (30)':                                     ('Item',     ItemClass.Junk,         0x4B, None),
    'Rupee (1)':                                       ('Item',     ItemClass.Junk,         0x4C, None),
    'Rupees (5)':                                      ('Item',     ItemClass.Junk,         0x4D, None),
    'Rupees (20)':                                     ('Item',     ItemClass.Junk,         0x4E, None),
    'Heart Container (Boss)':                          ('Item',     ItemClass.Normal,       0x4F, None),
    'Milk':                                            ('Item',     ItemClass.Normal,       0x50, None),
    'Goron Mask':                                      ('Item',     ItemClass.Normal,       0x51, None),
    'Zora Mask':                                       ('Item',     ItemClass.Normal,       0x52, None),
    'Gerudo Mask':                                     ('Item',     ItemClass.Normal,       0x53, None),
    'Rupees (50)':                                     ('Item',     ItemClass.Junk,         0x55, None),
    'Rupees (200)':                                    ('Item',     ItemClass.Normal,       0x56, None),
    'Biggoron Sword':                                  ('Item',     ItemClass.Advancement,  0x57, None),
    'Fire Arrows':                                     ('Item',     ItemClass.Advancement,  0x58, None),
    'Ice Arrows':                                      ('Item',     ItemClass.Normal,       0x59, None),
    'Light Arrows':                                    ('Item',     ItemClass.Advancement,  0x5A, None),
    'Gold Skulltula Token':                            ('Token',    ItemClass.Advancement,  0x5B, {'progressive': float('Inf')}),
    'Dins Fire':                                       ('Item',     ItemClass.Advancement,  0x5C, None),
    'Nayrus Love':                                     ('Item',     ItemClass.Advancement,  0x5E, None),
    'Farores Wind':                                    ('Item',     ItemClass.Advancement,  0x5D, None),
    'Deku Nuts (10)':                                  ('Item',     ItemClass.Junk,         0x64, None),
    'Bombs (10)':                                      ('Item',     ItemClass.Junk,         0x66, None),
    'Bombs (20)':                                      ('Item',     ItemClass.Junk,         0x67, None),
    'Deku Seeds (30)':                                 ('Item',     ItemClass.Junk,         0x69, None),
    'Bombchus (5)':                                    ('Item',     ItemClass.Advancement,  0x6A, None),
    'Bombchus (20)':                                   ('Item',     ItemClass.Advancement,  0x6B, None),
    'Rupee (Treasure Chest Game)':                     ('Item',     ItemClass.Normal,       0x72, None),
    'Piece of Heart (Treasure Chest Game)':            ('Item',     ItemClass.Normal,       0x76, None),
    'Ice Trap':                                        ('Item',     ItemClass.Junk,         0x7C, None),
    'Progressive Hookshot':                            ('Item',     ItemClass.Advancement,  0x80, {'progressive': 2}),
    'Progressive Strength Upgrade':                    ('Item',     ItemClass.Advancement,  0x81, {'progressive': 3}),
    'Bomb Bag':                                        ('Item',     ItemClass.Advancement,  0x82, None),
    'Bow':                                             ('Item',     ItemClass.Advancement,  0x83, None),
    'Slingshot':                                       ('Item',     ItemClass.Advancement,  0x84, None),
    'Progressive Wallet':                              ('Item',     ItemClass.Advancement,  0x85, {'progressive': 3}),
    'Progressive Scale':                               ('Item',     ItemClass.Advancement,  0x86, {'progressive': 2}),
    'Deku Nut Capacity':                               ('Item',     ItemClass.Normal,       0x87, None),
    'Deku Stick Capacity':                             ('Item',     ItemClass.Normal,       0x88, None),
    'Bombchus':                                        ('Item',     ItemClass.Advancement,  0x89, None),
    'Magic Meter':                                     ('Item',     ItemClass.Advancement,  0x8A, None),
    'Ocarina':                                         ('Item',     ItemClass.Advancement,  0x8B, None),
    'Bottle with Red Potion':                          ('Item',     ItemClass.Advancement,  0x8C, {'bottle': True, 'shop_object': 0x0F}),
    'Bottle with Green Potion':                        ('Item',     ItemClass.Advancement,  0x8D, {'bottle': True, 'shop_object': 0x0F}),
    'Bottle with Blue Potion':                         ('Item',     ItemClass.Advancement,  0x8E, {'bottle': True, 'shop_object': 0x0F}),
    'Bottle with Fairy':                               ('Item',     ItemClass.Advancement,  0x8F, {'bottle': True, 'shop_object': 0x0F}),
    'Bottle with Fish':                                ('Item',     ItemClass.Advancement,  0x90, {'bottle': True, 'shop_object': 0x0F}),
    'Bottle with Blue Fire':                           ('Item',     ItemClass.Advancement,  0x91, {'bottle': True, 'shop_object': 0x0F}),
    'Bottle with Bugs':                                ('Item',     ItemClass.Advancement,  0x92, {'bottle': True, 'shop_object': 0x0F}),
    'Bottle with Big Poe':                             ('Item',     ItemClass.Advancement,  0x93, {'shop_object': 0x0F}),
    'Bottle with Poe':                                 ('Item',     ItemClass.Advancement,  0x94, {'bottle': True, 'shop_object': 0x0F}),
    'Boss Key (Forest Temple)':                        ('BossKey',  ItemClass.Advancement,  0x95, None),
    'Boss Key (Fire Temple)':                          ('BossKey',  ItemClass.Advancement,  0x96, None),
    'Boss Key (Water Temple)':                         ('BossKey',  ItemClass.Advancement,  0x97, None),
    'Boss Key (Spirit Temple)':                        ('BossKey',  ItemClass.Advancement,  0x98, None),
    'Boss Key (Shadow Temple)':                        ('BossKey',  ItemClass.Advancement,  0x99, None),
    'Boss Key (Ganons Castle)':                   ('GanonBossKey',  ItemClass.Advancement,  0x9A, None),
    'Compass (Deku Tree)':                             ('Compass',  ItemClass.Normal,       0x9B, None),
    'Compass (Dodongos Cavern)':                       ('Compass',  ItemClass.Normal,       0x9C, None),
    'Compass (Jabu Jabus Belly)':                      ('Compass',  ItemClass.Normal,       0x9D, None),
    'Compass (Forest Temple)':                         ('Compass',  ItemClass.Normal,       0x9E, None),
    'Compass (Fire Temple)':                           ('Compass',  ItemClass.Normal,       0x9F, None),
    'Compass (Water Temple)':                          ('Compass',  ItemClass.Normal,       0xA0, None),
    'Compass (Spirit Temple)':                         ('Compass',  ItemClass.Normal,       0xA1, None),
    'Compass (Shadow Temple)':                         ('Compass',  ItemClass.Normal,       0xA2, None),
    'Compass (Bottom of the Well)':                    ('Compass',  ItemClass.Normal,       0xA3, None),
    'Compass (Ice Cavern)':                            ('Compass',  ItemClass.Normal,       0xA4, None),
    'Map (Deku Tree)':                                 ('Map',      ItemClass.Normal,       0xA5, None),
    'Map (Dodongos Cavern)':                           ('Map',      ItemClass.Normal,       0xA6, None),
    'Map (Jabu Jabus Belly)':                          ('Map',      ItemClass.Normal,       0xA7, None),
    'Map (Forest Temple)':                             ('Map',      ItemClass.Normal,       0xA8, None),
    'Map (Fire Temple)':                               ('Map',      ItemClass.Normal,       0xA9, None),
    'Map (Water Temple)':                              ('Map',      ItemClass.Normal,       0xAA, None),
    'Map (Spirit Temple)':                             ('Map',      ItemClass.Normal,       0xAB, None),
    'Map (Shadow Temple)':                             ('Map',      ItemClass.Normal,       0xAC, None),
    'Map (Bottom of the Well)':                        ('Map',      ItemClass.Normal,       0xAD, None),
    'Map (Ice Cavern)':                                ('Map',      ItemClass.Normal,       0xAE, None),
    'Small Key (Forest Temple)':                       ('SmallKey', ItemClass.Advancement,  0xAF, {'progressive': float('Inf')}),
    'Small Key (Fire Temple)':                         ('SmallKey', ItemClass.Advancement,  0xB0, {'progressive': float('Inf')}),
    'Small Key (Water Temple)':                        ('SmallKey', ItemClass.Advancement,  0xB1, {'progressive': float('Inf')}),
    'Small Key (Spirit Temple)':                       ('SmallKey', ItemClass.Advancement,  0xB2, {'progressive': float('Inf')}),
    'Small Key (Shadow Temple)':                       ('SmallKey', ItemClass.Advancement,  0xB3, {'progressive': float('Inf')}),
    'Small Key (Bottom of the Well)':                  ('SmallKey', ItemClass.Advancement,  0xB4, {'progressive': float('Inf')}),
    'Small Key (Gerudo Training Grounds)':             ('SmallKey', ItemClass.Advancement,  0xB5, {'progressive': float('Inf')}),
    'Small Key (Gerudo Fortress)':             ('FortressSmallKey', ItemClass.Advancement,  0xB6, {'progressive': float('Inf')}),
    'Small Key (Ganons Castle)':                       ('SmallKey', ItemClass.Advancement,  0xB7, {'progressive': float('Inf')}),
    'Double Defense':                                  ('Item',     ItemClass.Advancement,  0xB8, None),
    'Magic Bean Pack':                                 ('Item',     ItemClass.Advancement,  0xC9, None),
    'Triforce Piece':                                  ('Item',     ItemClass.Advancement,  0xCA, {'progressive': float('Inf')}),
    'Zeldas Letter':                                   ('Item',     ItemClass.Advancement,  0x0B, None),
    'Time Travel':                                     ('Event',    ItemClass.Advancement,  None, None),
    'Scarecrow Song':                                  ('Event',    ItemClass.Advancement,  None, None),
    'Triforce':                                        ('Event',    ItemClass.Advancement,  None, None),

    # Event items otherwise generated by generic event logic
    # can be defined here to enforce their appearance in playthroughs.
    'Water Temple Clear':               ('Event',    ItemClass.Advancement,  None, None),
    'Forest Trial Clear':               ('Event',    ItemClass.Advancement,  None, None),
    'Fire Trial Clear':                 ('Event',    ItemClass.Advancement,  None, None),
    'Water Trial Clear':                ('Event',    ItemClass.Advancement,  None, None),
    'Shadow Trial Clear':               ('Event',    ItemClass.Advancement,  None, None),
    'Spirit Trial Clear':               ('Event',    ItemClass.Advancement,  None, None),
    'Light Trial Clear':                ('Event',    ItemClass.Advancement,  None, None),

    'Deku Stick Drop':                  ('Drop',     ItemClass.Advancement,  None, None),
    'Deku Nut Drop':                    ('Drop',     ItemClass.Advancement,  None, None),
    'Blue Fire':                        ('Drop',     ItemClass.Advancement,  None, None),
    'Fairy':                            ('Drop',     ItemClass.Advancement,  None, None),
    'Fish':                             ('Drop',     ItemClass.Advancement,  None, None),
    'Bugs':                             ('Drop',     ItemClass.Advancement,  None, None),
    'Big Poe':                          ('Drop',     ItemClass.Advancement,  None, None),
    'Bombchu Drop':                     ('Drop',     ItemClass.Advancement,  None, None),

    # Consumable refills defined mostly to placate 'starting with' options
    'Arrows':                           ('Refill',   ItemClass.Normal,       None, None),
    'Bombs':                            ('Refill',   ItemClass.Normal,       None, None),
    'Deku Seeds':                       ('Refill',   ItemClass.Normal,       None, None),
    'Deku Sticks':                      ('Refill',   ItemClass.Normal,       None, None),
    'Deku Nuts':                        ('Refill',   ItemClass.Normal,       None, None),
    'Rupees':                           ('Refill',   ItemClass.Normal,       None, None),

    'Minuet of Forest':                 ('Song',  ItemClass.Advancement,  0xBB,
                                            {
                                                'text_id': 0x73,
                                                'song_id': 0x02,
                                                'item_id': 0x5A,
                                            }),
    'Bolero of Fire':                   ('Song',  ItemClass.Advancement,  0xBC,
                                            {
                                                'text_id': 0x74,
                                                'song_id': 0x03,
                                                'item_id': 0x5B,
                                            }),
    'Serenade of Water':                ('Song',  ItemClass.Advancement,  0xBD,
                                            {
                                                'text_id': 0x75,
                                                'song_id': 0x04,
                                                'item_id': 0x5C,
                                            }),
    'Requiem of Spirit':                ('Song',  ItemClass.Advancement,  0xBE,
                                            {
                                                'text_id': 0x76,
                                                'song_id': 0x05,
                                                'item_id': 0x5D,
                                            }),
    'Nocturne of Shadow':               ('Song',  ItemClass.Advancement,  0xBF,
                                            {
                                                'text_id': 0x77,
                                                'song_id': 0x06,
                                                'item_id': 0x5E,
                                            }),
    'Prelude of Light':                 ('Song',  ItemClass.Advancement,  0xC0,
                                            {
                                                'text_id': 0x78,
                                                'song_id': 0x07,
                                                'item_id': 0x5F,
                                            }),
    'Zeldas Lullaby':                   ('Song',  ItemClass.Advancement,  0xC1,
                                            {
                                                'text_id': 0xD4,
                                                'song_id': 0x0A,
                                                'item_id': 0x60,
                                            }),
    'Eponas Song':                      ('Song',  ItemClass.Advancement,  0xC2,
                                            {
                                                'text_id': 0xD2,
                                                'song_id': 0x09,
                                                'item_id': 0x61,
                                            }),
    'Sarias Song':                      ('Song',  ItemClass.Advancement,  0xC3,
                                            {
                                                'text_id': 0xD1,
                                                'song_id': 0x08,
                                                'item_id': 0x62,
                                            }),
    'Suns Song':                        ('Song',  ItemClass.Advancement,  0xC4,
                                            {
                                                'text_id': 0xD3,
                                                'song_id': 0x0B,
                                                'item_id': 0x63,
                                            }),
    'Song of Time':                     ('Song',  ItemClass.Advancement,  0xC5,
                                            {
                                                'text_id': 0xD5,
                                                'song_id': 0x0C,
                                                'item_id': 0x64,
                                            }),
    'Song of Storms':                   ('Song',  ItemClass.Advancement,  0xC6,
                                            {
                                                'text_id': 0xD6,
                                                'song_id': 0x0D,
                                                'item_id': 0x65,
                                            }),

    'Buy Deku Nut (5)':                 ('Shop',     ItemClass.Advancement,  0x00, {'object': 0x00BB, 'price': 15}),
    'Buy Arrows (30)':                  ('Shop',     ItemClass.Priority,     0x01, {'object': 0x00D8, 'price': 60}),
    'Buy Arrows (50)':                  ('Shop',     ItemClass.Priority,     0x02, {'object': 0x00D8, 'price': 90}),
    'Buy Bombs (5) [25]':               ('Shop',     ItemClass.Priority,     0x03, {'object': 0x00CE, 'price': 25}),
    'Buy Deku Nut (10)':                ('Shop',     ItemClass.Advancement,  0x04, {'object': 0x00BB, 'price': 30}),
    'Buy Deku Stick (1)':               ('Shop',     ItemClass.Advancement,  0x05, {'object': 0x00C7, 'price': 10}),
    'Buy Bombs (10)':                   ('Shop',     ItemClass.Priority,     0x06, {'object': 0x00CE, 'price': 50}),
    'Buy Fish':                         ('Shop',     ItemClass.Advancement,  0x07, {'object': 0x00F4, 'price': 200}),
    'Buy Red Potion [30]':              ('Shop',     ItemClass.Priority,     0x08, {'object': 0x00EB, 'price': 30}),
    'Buy Green Potion':                 ('Shop',     ItemClass.Priority,     0x09, {'object': 0x00EB, 'price': 30}),
    'Buy Blue Potion':                  ('Shop',     ItemClass.Priority,     0x0A, {'object': 0x00EB, 'price': 100}),
    'Buy Hylian Shield':                ('Shop',     ItemClass.Advancement,  0x0C, {'object': 0x00DC, 'price': 80}),
    'Buy Deku Shield':                  ('Shop',     ItemClass.Advancement,  0x0D, {'object': 0x00CB, 'price': 40}),
    'Buy Goron Tunic':                  ('Shop',     ItemClass.Advancement,  0x0E, {'object': 0x00F2, 'price': 200}),
    'Buy Zora Tunic':                   ('Shop',     ItemClass.Advancement,  0x0F, {'object': 0x00F2, 'price': 300}),
    'Buy Heart':                        ('Shop',     ItemClass.Priority,     0x10, {'object': 0x00B7, 'price': 10}),
    'Buy Bombchu (10)':                 ('Shop',     ItemClass.Advancement,  0x15, {'object': 0x00D9, 'price': 99}),
    'Buy Bombchu (20)':                 ('Shop',     ItemClass.Advancement,  0x16, {'object': 0x00D9, 'price': 180}),
    'Buy Bombchu (5)':                  ('Shop',     ItemClass.Advancement,  0x18, {'object': 0x00D9, 'price': 60}),
    'Buy Deku Seeds (30)':              ('Shop',     ItemClass.Priority,     0x1D, {'object': 0x0119, 'price': 30}),
    'Sold Out':                         ('Shop',     ItemClass.Priority,     0x26, {'object': 0x0148}),
    'Buy Blue Fire':                    ('Shop',     ItemClass.Advancement,  0x27, {'object': 0x0173, 'price': 300}),
    'Buy Bottle Bug':                   ('Shop',     ItemClass.Advancement,  0x28, {'object': 0x0174, 'price': 50}),
    'Buy Poe':                          ('Shop',     ItemClass.Priority,     0x2A, {'object': 0x0176, 'price': 30}),
    "Buy Fairy's Spirit":               ('Shop',     ItemClass.Advancement,  0x2B, {'object': 0x0177, 'price': 50}),
    'Buy Arrows (10)':                  ('Shop',     ItemClass.Priority,     0x2C, {'object': 0x00D8, 'price': 20}),
    'Buy Bombs (20)':                   ('Shop',     ItemClass.Priority,     0x2D, {'object': 0x00CE, 'price': 80}),
    'Buy Bombs (30)':                   ('Shop',     ItemClass.Priority,     0x2E, {'object': 0x00CE, 'price': 120}),
    'Buy Bombs (5) [35]':               ('Shop',     ItemClass.Priority,     0x2F, {'object': 0x00CE, 'price': 35}),
    'Buy Red Potion [40]':              ('Shop',     ItemClass.Priority,     0x30, {'object': 0x00EB, 'price': 40}),
    'Buy Red Potion [50]':              ('Shop',     ItemClass.Priority,     0x31, {'object': 0x00EB, 'price': 50}),

    'Kokiri Emerald':                   ('DungeonReward',  ItemClass.Advancement,  None,
                                            {
                                                'stone':      True,
                                                'addr2_data': 0x80,
                                                'bit_mask':   0x00040000,
                                                'item_id':    0x6C,
                                                'actor_type': 0x13,
                                                'object_id':  0x00AD,
                                            }),
    'Goron Ruby':                       ('DungeonReward',  ItemClass.Advancement,  None,
                                            {
                                                'stone':      True,
                                                'addr2_data': 0x81,
                                                'bit_mask':   0x00080000,
                                                'item_id':    0x6D,
                                                'actor_type': 0x14,
                                                'object_id':  0x00AD,
                                            }),
    'Zora Sapphire':                    ('DungeonReward',  ItemClass.Advancement,  None,
                                            {
                                                'stone':      True,
                                                'addr2_data': 0x82,
                                                'bit_mask':   0x00100000,
                                                'item_id':    0x6E,
                                                'actor_type': 0x15,
                                                'object_id':  0x00AD,
                                            }),
    'Forest Medallion':                 ('DungeonReward',  ItemClass.Advancement,  None,
                                            {
                                                'medallion':  True,
                                                'addr2_data': 0x3E,
                                                'bit_mask':   0x00000001,
                                                'item_id':    0x66,
                                                'actor_type': 0x0B,
                                                'object_id':  0x00BA,
                                            }),
    'Fire Medallion':                   ('DungeonReward',  ItemClass.Advancement,  None,
                                            {
                                                'medallion':  True,
                                                'addr2_data': 0x3C,
                                                'bit_mask':   0x00000002,
                                                'item_id':    0x67,
                                                'actor_type': 0x09,
                                                'object_id':  0x00BA,
                                            }),
    'Water Medallion':                  ('DungeonReward',  ItemClass.Advancement,  None,
                                            {
                                                'medallion':  True,
                                                'addr2_data': 0x3D,
                                                'bit_mask':   0x00000004,
                                                'item_id':    0x68,
                                                'actor_type': 0x0A,
                                                'object_id':  0x00BA,
                                            }),
    'Spirit Medallion':                 ('DungeonReward',  ItemClass.Advancement,  None,
                                            {
                                                'medallion':  True,
                                                'addr2_data': 0x3F,
                                                'bit_mask':   0x00000008,
                                                'item_id':    0x69,
                                                'actor_type': 0x0C,
                                                'object_id':  0x00BA,
                                            }),
    'Shadow Medallion':                 ('DungeonReward',  ItemClass.Advancement,  None,
                                            {
                                                'medallion':  True,
                                                'addr2_data': 0x41,
                                                'bit_mask':   0x00000010,
                                                'item_id':    0x6A,
                                                'actor_type': 0x0D,
                                                'object_id':  0x00BA,
                                            }),
    'Light Medallion':                  ('DungeonReward',  ItemClass.Advancement,  None,
                                            {
                                                'medallion':  True,
                                                'addr2_data': 0x40,
                                                'bit_mask':   0x00000020,
                                                'item_id':    0x6B,
                                                'actor_type': 0x0E,
                                                'object_id':  0x00BA,
                                            }),
}
